### ISSUE TITLE
Deccan Delight not working 

### ISSUE THREAD

**Issue by alikader** [Gujal00/GujalKodiWork#12]
hi,
Any problem with Deccan Delight, after the update. All files disappeared.

**Comment by Gujal00** [comment]
Is it really not working in Kodi? The distribution zip files and addons.xml is still here

**Comment by alikader** [comment]
Yes, it does not work in Kodi after update.
See this quick video link. 
May help you where the problem is.
https://drive.google.com/file/d/1ktVKy1ppq3vt2FBJgfBMn-6D3FLVBlArjg/view?usp=sharing

**Comment by Gujal00** [comment]
Yes, two things
1. You need to install the latest repository file from zip
The repository zip is here https://github.com/Gujal00/GujalKodiWork/releases/download/1.6/repository.gujal-1.6.zip
Once you install the new repository DD should get updated to 1.4.0. You are currently having 1.3.8 which is two releases behind.

2. MHDTV has gone paid so wont work. Switch it off in the addon settings.

**Comment by alikader** [comment]
Yes Working. Thanks. I had to delete and reinstall to get the update for some reasons.
Thanks

**Comment by johnakash** [comment]
Could you please tell me the latest steps to configure Deccan Delight in fire tv stick?

**Comment by kuku45** [comment]
I cannot see latest serials on my PC. The Colors and Zee serials are atlas 4 days old. I can see on my cell phone running kodi

**Comment by Gujal00** [comment]
Why are you adding a comment to an issue closed 6 months ago? If you have a new issue, please raise a new one instead of adding comment to a closed issue as it will show up as a pending issue to be resolved.
Anyway two other people have reported the same issue and they are in open state. Will be resolved in the next release
Also what versions are running on your PC and on your cellphone? Just saying it is not working is not helpful

**Comment by maddy0907** [comment]
Could you plz post steps to configure Deccan delight in fire stick

**Comment by Gujal00** [comment]
@maddy0907 why would you comment on a issue closed 6 months ago? Use a new issue
Read this #45
