### ISSUE TITLE
Deccan Delight - Tamil Yogi - not pulling updates

### ISSUE THREAD

**Issue by SunFloWeR15** [Gujal00/GujalKodiWork#55]
Hi Bro, Deccan Delight > Tamil Yogi > not pulling latest content at all. It works when the TV box is flatten and rebuilt with factory settings, and install kodi, then Deccan Delight. After couple of days, there were couple of notifications on request dependencies and post that it starts failing.
Platform: Android app version
Please look into it..

**Comment by SunFloWeR15** [comment]
Observation: When Clear Cache (clear_cache()) in Deccan Delight is hit, then getting the new content.. looks like need to clear cache before list_second(), not sure how it was working pulling before 1.5.7.

**Comment by Gujal00** [comment]
what platform are you running (Windows/Android/IOS/Linux/MacOS)?
I test it in Windows and Android under Kodi 17.6 and works fine for me.

**Comment by SunFloWeR15** [comment]
It is Jarvis 16.1, Android

**Comment by Gujal00** [comment]
Unfortunately Kodi < 17 on Android has ancient Python 2.6 in it and can't be supported anymore
See if you can go to Kodi 17.6. However if you are on Android 4.4 then you can't use Kodi 17.x
The only option for you is FTMC which is custom Jarvis version with Python updated to 2.7.11 or install MyGica which is Kodi 17.x variant that can be installed on Android 4.4

I cannot support Jarvis on Android due to legacy python issue

**Comment by SunFloWeR15** [comment]
Ok, got it..I am moving to mygica, please close the issue.

**Comment by Gujal00** [comment]
Check on MyGica and report if working or not. I will close the issue once you confirm

**Comment by Gujal00** [comment]
I have reverted to the caching mechanism in DD 1.5.9 as used in earlier versions. Should work in Android Jarvis as before.
