### ISSUE TITLE
Deccan delight 1.5.8 not working

### ISSUE THREAD

**Issue by me30122** [Gujal00/GujalKodiWork#59]
After updating automatically to version 1.5.8 Deccan delight add on not working even it’s not opening up and giving error. Can you please check.

**Comment by me30122** [comment]
Using Kodi 17.6 on Firestick. Was working fine till the 1.5.8 update

**Comment by Gujal00** [comment]
please upload the logfile and provide the link. It is diffiicult to diagnose without it, as 1.58 works fine on Kodi 17.6 Windows 8&10 and MXIII+ Android 5.1 (the only platforms that I have)

**Comment by me30122** [comment]
Hi Gujal please check log 
https://paste.kodi.tv/qinuwigepe

**Comment by Gujal00** [comment]
It is not a Deccan Delight issue. YOu have installed various wizards which have overwritten ResolveURL and Youtube-dl COntrol addons (both of which are used by DD)
ResolveURL is from JSergio and the official version is 5.0.10, you seem to have 6.0.09????
The error is because of incorrect youtube-dl, it should be from official kodi repo and version 18.425.0 and will work.
I am closing this as it is because of your particular Kodi build and not a DD issue.
