### ISSUE TITLE
Hotstar Addon not working !

### ISSUE THREAD

**Issue by plikmuny** [Gujal00/GujalKodiWork#75]
Hi Gujal, Hotstar is not working from the past few days. Can you pls look into it. Thanks.

**Comment by sandyriverr** [comment]
Hi gujal,
Thanks for all your efforts. Adding my comment here because it pertains to hotstar. Recently , they have changed the hotstar latest shows to not work through the addon. Im able to see big boss show of last year but not able to watch this year episodes. Will you be able to figure how to bypass that? Thanks again.

**Comment by Gujal00** [comment]
This is because of Hotstar enforcing geo-restriction and nothing to do with the addon. It will only work with India VPN now. Just adding India IP is no good for the new shows.
I already answered about this on the hotstar thread
`https://forum.kodi.tv/showthread.php?tid=241506&page=30`

Why open issue here, when you should be opening in YoColdrain's github as he is the author
https://github.com/YoColdRain/Hotstar-Rain/issues

Closing this issue as I cannot do anything about it
